name: "Create Pull Request"
description: "Create a pull request"
inputs:
  # repo & auth
  repository:
    description: 'Target repository (owner/name)'
    required: true
  ref:
    description: 'Git ref to check out'
    required: false
  token:
    description: 'Repo token with repo and PR permissions'
    required: false
  lfs:
    description: 'Whether to enable LFS support'
    required: false
    default: 'true'
  submodules:
    description: 'Whether to enable submodules'
    required: false
    default: 'false'
  github-server-url:
    description: 'Git server URL (e.g., https://github.com)'
    required: false
    default: 'https://github.com'

  # SSH
  ssh-private-key:
    description: 'SSH private key for deploy-key'
    required: false

  # just
  just-version:
    description: 'just version to install'
    required: false
    default: '*'
  just-install:
    description: 'Whether to install just'
    required: false
    default: 'false'

  # command
  command:
    description: 'Command to run after checkout'
    required: false
    default: 'just deps-sync'

  # PR metadata
  branch:
    description: 'Branch name for the PR'
    required: false
  commit-message:
    description: 'Commit message for deps changes'
    required: false
    default: 'ci: automated action'
  title:
    description: 'Pull request title'
    required: false
    default: 'Automated PR'
  body:
    description: 'Pull request body'
    required: false
    default: 'This PR was automatically generated'
  add-paths:
    description: 'Paths to include in the PR'
    required: false
  committer:
    description: 'Committer identity'
    required: false
  author:
    description: 'Author identity'
    required: false
  labels:
    description: 'Labels to add to the PR'
    required: false
  assignees:
    description: 'Assignees for the PR'
    required: false
  reviewers:
    description: 'Reviewers for the PR'
    required: false

  # auto-merge
  auto-merge:
    description: 'Whether to enable auto-merge'
    required: false
    default: 'true'
  merge-method:
    description: 'Auto-merge method (merge, squash, rebase)'
    required: false
    default: 'squash'

runs:
  using: composite
  steps:
    - name: Install just
      if: inputs.just-install == 'true'
      uses: extractions/setup-just@v3
      with:
        just-version: ${{ inputs.just-version }}

    - name: Setup deploy key
      if: inputs.ssh-private-key != ''
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    - name: Check out target repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}
        lfs: ${{ inputs.lfs }}
        submodules: ${{ inputs.submodules }}
        github-server-url: ${{ inputs.github-server-url }}

    - name: Run deps sync
      shell: bash
      run: ${{ inputs.command }}

    - name: Create pull request
      id: cpr
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ inputs.token }}
        branch: ${{ inputs.branch }}
        add-paths: ${{ inputs.add-paths }}
        committer: ${{ inputs.committer }}
        author: ${{ inputs.author }}
        labels: ${{ inputs.labels }}
        assignees: ${{ inputs.assignees }}
        reviewers: ${{ inputs.reviewers }}
        commit-message: ${{ inputs.commit-message }}
        title: ${{ inputs.title }}
        body: ${{ inputs.body }}

    - name: Enable PR auto-merge
      if: |
        steps.cpr.outputs.pull-request-operation == 'created' &&
        inputs.auto-merge == 'true'
      uses: peter-evans/enable-pull-request-automerge@v3
      with:
        token: ${{ inputs.token }}
        repository: ${{ inputs.repository }}
        pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
        merge-method: ${{ inputs.merge-method }}
