name: Buildx Bake
description: Build container images using buildx bake
inputs:
  bake-file:
    description: 'The bake file'
    required: false
    default: 'docker-bake.hcl'
  bake-push:
    description: 'Push the image'
    required: false
    default: "true"
  bake-targets:
    description: 'The bake target'
    required: false
    default: 'build'
  bake-set:
    description: 'The bake set'
    required: false
    default: |
      *.cache-to=type=gha,ignore-error=true,mode=max
      *.cache-from=type=gha
  bake-extra-files:
    description: 'Extra files to include in buildx bake'
    required: false
  meta-tags:
    description: 'The tags to add to the image'
    required: true
  meta-labels:
    description: 'The labels to add to the image'
    required: false
  registry:
    description: 'The container registry'
    required: false
    default: 'ghcr.io'
  registry-image:
    description: 'Container registry + image prefix (e.g. ghcr.io/org/repo)'
    required: false
    default: ghcr.io/${{ github.repository }}
  registry-username:
    description: 'The container registry username'
    required: true
    default: ${{ github.actor }}
  registry-password:
    description: 'The container registry password'
    required: true
outputs:
  metadata:
    description: 'The bake metadata of the built image'
    value: ${{ steps.bake.outputs.metadata }}
runs:
  using: "composite"
  steps:
    - name: Convert registry-image to lowercase
      shell: bash
      id: lowercase_registry_image
      run: |
        echo "registry-image=${{ inputs.registry-image }}" | tr '[:upper:]' '[:lower:]' >> "$GITHUB_OUTPUT"

    - name: Create matrix
      shell: bash
      id: platforms
      run: |
        echo "matrix=$(docker buildx bake ${{ inputs.bake-targets }} --print | jq -cr '.target."${{ inputs.bake-targets }}".platforms')" >>${GITHUB_OUTPUT}

    - name: Show matrix
      shell: bash
      run: |
        echo ${{ steps.platforms.outputs.matrix }}

    - name: Set up qemu
      uses: docker/setup-qemu-action@v3

    - name: Set up docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract metadata (tags, labels) for image
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ steps.lowercase_registry_image.outputs.registry-image }}
        tags: ${{ inputs.meta-tags }}
        labels: ${{ inputs.meta-labels }}

    - name: Log in to the container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}

    - name: Build container image
      id: bake
      uses: docker/bake-action@v5
      env:
        IMAGE_NAME: ${{ steps.lowercase_registry_image.outputs.registry-image }}
      with:
        files: |
          ./${{ inputs.bake-file }}
          ${{ steps.meta.outputs.bake-file }}
          ${{ inputs.bake-extra-files }}
        push: ${{ inputs.bake-push }}
        targets: ${{ inputs.bake-targets }}
        set: ${{ inputs.bake-set }}
