name: Release Version
description: Set release version
inputs:
  version-previous:
    description: 'The strategy to detect the previous version: auto, from-tag, from-file or manual'
    required: false
    default: 'auto'
  version-next:
    description: 'The strategy to calculate the next version: auto, semantic, from-file, increment or manual'
    required: false
    default: 'auto'
  version-output-format:
    description: 'The output format of the next version'
    required: false
    default: '{{.Major}}.{{.Minor}}.{{.Patch}}'
  tag:
    description: 'If enabled, a new tag will be created'
    required: false
    default: 'false'
outputs:
  version:
    description: 'The next version (using semantic versioning)'
    value: ${{ steps.release_version.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Next release version
      id: release_version
      uses: jenkins-x-plugins/jx-release-version@v2.7.8
      with:
        previous-version: ${{ inputs.version-previous }}
        next-version: ${{ inputs.version-next }}
        output-format: ${{ version-output-format }}
        tag: ${{ inputs.tag }}
