name: Version File
description: Set version in file
inputs:
  VERSION:
    description: 'The version to set'
    required: true
  VERSION_FILE:
    description: 'Set version in VERSION file'
    required: false
    default: "false"
  VERSION_MAKEFILE:
    description: 'Set version in Makefile'
    required: false
    default: "false"
  VERSION_PACKAGE:
    description: 'Set version in package.json'
    required: false
    default: "false"
  VERSION_CHART:
    description: 'Set version in chart dir'
    required: false
    default: "false"
  REPO_NAME:
    description: 'The name of the repository'
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: set version in file
      shell: bash
      run: |
        if [ "${{ inputs.VERSION_FILE }}" == "true" ]; then
          echo "Set version in VERSION file to: ${{ inputs.VERSION }}"
          echo $VERSION > VERSION
        fi
        if [ "${{ inputs.VERSION_MAKEFILE }}" == "true" ]; then
          echo "Set version in Makefile to: ${{ inputs.VERSION }}"
          sed -i "s@^VERSION .*@VERSION ?= ${{ inputs.VERSION }}@" Makefile
        fi
        if [ "${{ inputs.VERSION_PACKAGE }}" == "true" ]; then
          echo "Set version in package.json to: ${{ inputs.VERSION }}"
          sed -i "s@\"version\":.*@\"version\": \"${{ inputs.VERSION }}\",@" package.json
        fi
        if [ "${{ inputs.VERSION_CHART }}" == "true" ] && [ -n "${{ inputs.REPO_NAME }}" ]; then
          echo "Set version in chart dir to: ${{ inputs.VERSION }}"
          sed -i "s/^version:.*/version: ${{ inputs.VERSION }}/" charts/${{ inputs.REPO_NAME }}/Chart.yaml
          sed -i "s/tag:.*/tag: ${{ inputs.VERSION }}/" charts/${{ inputs.REPO_NAME }}/values.yaml
        fi
