name: Version File
description: Set version in file
inputs:
  version:
    description: 'The version to set'
    required: true
  version-file:
    description: 'Set version in file named as input'
    required: false
  version-makefile:
    description: 'Set version in makefile named as input'
    required: false
  version-justfile:
    description: 'Set version in justfile named as input'
    required: false
  version-package:
    description: 'Set version in package json named as input'
    required: false
  version-script:
    description: 'Set version in script named as input'
    required: false
  version-chart:
    description: 'Set version in chart named as input'
    required: false
runs:
  using: "composite"
  steps:
    - name: set version in file
      shell: bash
      run: |
        if [ -n "${{ inputs.version-file }}" ]; then
          echo "set version in file '${{ inputs.version-file }}' to: ${{ inputs.version }}"
          echo '${{ inputs.version }}' > "${{ inputs.version-file }}"
        fi
        if [ -n "${{ inputs.version-makefile }}" ]; then
          echo "set version in makefile '${{ inputs.version-makefile }}' to: ${{ inputs.version }}"
          sed -i "s@^VERSION .*@VERSION ?= ${{ inputs.version }}@" "${{ inputs.version-makefile }}"
        fi
        if [ -n "${{ inputs.version-justfile }}" ]; then
          echo "set version in justfile '${{ inputs.version-justfile }}' to: ${{ inputs.version }}"
          sed -i "s@^version .*@version := \"${{ inputs.version }}\"@" "${{ inputs.version-justfile }}"
        fi
        if [ -n "${{ inputs.version-package }}" ]; then
          echo "set version in file '${{ inputs.version-package }}' to: ${{ inputs.version }}"
          sed -i "s@\"version\":.*@\"version\": \"${{ inputs.version }}\",@" "${{ inputs.version-package }}"
        fi
        if [ -n "${{ inputs.version-script }}" ]; then
          echo "set version in script '${{ inputs.version-script }}' to: ${{ inputs.version }}"
          sed -i "s@^VERSION=.*@VERSION=${{ inputs.version }}@" "${{ inputs.version-script }}"
        fi
        if [ -n "${{ inputs.version-chart }}" ]; then
          echo "set version in chart '${{ inputs.version-chart }}' to: ${{ inputs.version }}"
          sed -i "s/^version:.*/version: ${{ inputs.version }}/" charts/${{ inputs.version-chart }}/Chart.yaml
          sed -i "s/tag:.*/tag: ${{ inputs.version }}/" charts/${{ inputs.version-chart }}/values.yaml
        fi
