name: Version File
description: Set version in file
inputs:
  version:
    description: 'The version to set'
    required: true
  version-file:
    description: 'Set version in VERSION file'
    required: false
    default: "false"
  version-makefile:
    description: 'Set version in Makefile'
    required: false
    default: "false"
  version-package:
    description: 'Set version in package.json'
    required: false
    default: "false"
  version-script:
    description: 'Set version in script'
    required: false
    default: ""
  version-chart:
    description: 'Set version in chart dir'
    required: false
    default: "false"
  repo-name:
    description: 'The name of the repository'
    required: false
    default: ""
  make-target:
    description: 'The make target to run'
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: set version in file
      shell: bash
      run: |
        if [ "${{ inputs.version-file }}" == "true" ]; then
          echo "Set version in VERSION file to: ${{ inputs.version }}"
          echo '${{ inputs.version }}' > VERSION
        fi
        if [ "${{ inputs.version-makefile }}" == "true" ]; then
          echo "Set version in Makefile to: ${{ inputs.version }}"
          sed -i "s@^VERSION .*@VERSION ?= ${{ inputs.version }}@" Makefile
        fi
        if [ "${{ inputs.version-package }}" == "true" ]; then
          echo "Set version in package.json to: ${{ inputs.version }}"
          sed -i "s@\"version\":.*@\"version\": \"${{ inputs.version }}\",@" package.json
        fi
        if [ -n "${{ inputs.version-script }}" ]; then
          echo "Set version in script '${{ inputs.version-script }}' to: ${{ inputs.version }}"
          sed -i "s@^VERSION=.*@VERSION=${{ inputs.version }}@" ${{ inputs.version-script }}
        fi
        if [ "${{ inputs.version-chart }}" == "true" ] && [ -n "${{ inputs.repo-name }}" ]; then
          echo "Set version in chart dir to: ${{ inputs.version }}"
          sed -i "s/^version:.*/version: ${{ inputs.version }}/" charts/${{ inputs.repo-name }}/Chart.yaml
          sed -i "s/tag:.*/tag: ${{ inputs.version }}/" charts/${{ inputs.repo-name }}/values.yaml
        fi

    - name: run make target
      if: inputs.make-target != ''
      shell: bash
      run: |
        echo "Run make target: ${{ inputs.make-target }}"
        make ${{ inputs.make-target }}
