name: Release Git Push
description: 'Push changes to the repository on a release'
inputs:
  version:
    description: 'The version to push'
    required: true
  git-user-name:
    description: 'The git user name'
    required: false
    default: 'github-actions[bot]'
  git-user-email:
    description: 'The git user email'
    required: false
    default: '41898282+github-actions[bot]@users.noreply.github.com'
  git-add-files:
    description: 'The files to add to git'
    required: false
runs:
  using: "composite"
  steps:
    - name: Push git version
      shell: bash
      env:
        TAG: ${{ inputs.version }}
        DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
      run: |
        set -euo pipefail
        push_target="HEAD"

        if [ "${GITHUB_REF_TYPE:-}" = "tag" ]; then
          push_target="HEAD:refs/heads/${DEFAULT_BRANCH}"
        fi

        git config user.name "${{ inputs.git-user-name }}"
        git config user.email "${{ inputs.git-user-email }}"
        git add ${{ inputs.git-add-files }}

        # Check if there are changes to commit
        if [ -z "$(git status --porcelain)" ]; then
          echo "No changes to commit"

          # Check if the target release tag already exists
          if [ -z "$(git tag -l "v${TAG}")" ]; then
            echo "Creating and pushing tag v${TAG}"
            git tag "v${TAG}"
            git push --atomic origin "v${TAG}"
          else
            echo "Tag v${TAG} already exists"
          fi
        else
          echo "Committing changes and pushing"
          git commit -m "chore: bump version to v${TAG}" -m "[skip ci]"
          git tag "v${TAG}"
          git push --atomic origin "${push_target}" "v${TAG}"
        fi
