name: Release Git Push
description: 'Push changes to the repository on a release'
inputs:
  version:
    description: 'The version to push'
    required: true
  git-user-name:
    description: 'The git user name'
    required: false
    default: 'github-actions[bot]'
  git-user-email:
    description: 'The git user email'
    required: false
    default: '41898282+github-actions[bot]@users.noreply.github.com'
  git-add-files:
    description: 'The files to add to git'
    required: false
runs:
  using: "composite"
  steps:
    - name: Push git version
      shell: bash
      env:
        TAG: ${{ inputs.version }}
      run: |
        set -euo pipefail
        git config user.name "${{ inputs.git-user-name }}"
        git config user.email "${{ inputs.git-user-email }}"
        git add ${{ inputs.git-add-files }}

        # Check if there are changes to commit
        if [ -z "$(git status --porcelain)" ]; then
          echo "No changes to commit"

          # Check if current commit has no tag at all
          if [ -z "$(git tag --points-at HEAD)" ]; then
            echo "Creating and pushing tag ${TAG}"
            git tag "${TAG}"
            git push --atomic origin HEAD "${TAG}"
          else
            echo "A tag already exists for this commit"
          fi
        else
          echo "Committing changes and pushing"
          git commit -m "chore: bump version to ${TAG}" -m "[skip ci]"
          git tag "${TAG}"
          git push --atomic origin HEAD "${TAG}"
        fi
