name: Pull request

on:
  workflow_call:
    outputs:
      version:
        description: 'The version of the pull-request'
        value: ${{ jobs.pull-request.outputs.version }}
    secrets:
      registry-password:
        description: 'The container registry password'
        required: true
    inputs:
      git-user-name:
        description: 'The git user name'
        required: false
        type: string
        default: 'github-actions[bot]'
      git-user-email:
        description: 'The git user email'
        required: false
        type: string
        default: '41898282+github-actions[bot]@users.noreply.github.com'
      git-add-files:
        description: 'The files to add to git'
        required: false
        type: string
      previous-version:
        description: 'The strategy to detect the previous version: auto, from-tag, from-file or manual'
        required: false
        default: 'auto'
        type: string
      next-version:
        description: 'The strategy to calculate the next version: auto, semantic, from-file, increment or manual'
        required: false
        default: 'auto'
        type: string
      output-format:
        description: 'The output format of the next version'
        required: false
        default: '{{.Major}}.{{.Minor}}.{{.Patch}}-pull-request'
        type: string
      version-file:
        description: 'Set version in file named as input'
        required: false
        type: string
      version-makefile:
        description: 'Set version in makefile named as input'
        required: false
        type: string
      version-justfile:
        description: 'Set version in justfile named as input'
        required: false
        type: string
      version-package:
        description: 'Set version in package json named as input'
        required: false
        type: string
      version-package-lock:
        description: 'Set version in package lock named as input'
        required: false
        type: string
      version-script:
        description: 'Set version in script named as input'
        required: false
        type: string
      version-chart:
        description: 'Set version in chart named as input'
        required: false
        type: string
      bake-file:
        description: 'The bake file'
        required: false
        default: 'docker-bake.hcl'
        type: string
      bake-push:
        description: 'Push the image'
        required: false
        default: true
        type: boolean
      bake-targets:
        description: 'The bake target'
        required: false
        default: 'build'
        type: string
      bake-set:
        description: 'The bake set'
        required: false
        type: string
        default: |
          *.cache-to=type=gha,ignore-error=true,mode=max
          *.cache-from=type=gha
      bake-extra-files:
        description: 'Extra files to include in buildx bake'
        required: false
        type: string
      image-name:
        description: 'The name of the image (without tag)'
        required: false
        default: ghcr.io/${{ github.repository }}
        type: string
      meta-tags:
        description: 'The tags to add to the image'
        required: false
        type: string
      meta-labels:
        description: 'The labels to add to the image'
        required: false
        type: string
      registry:
        description: 'The container registry'
        required: false
        default: 'ghcr.io'
        type: string
      registry-username:
        description: 'The container registry username'
        required: false
        default: ${{ github.actor }}
        type: string
      build-container-image-pre-command:
        description: 'The command to run before building the container image'
        required: false
        type: string
      just-install:
        description: 'Install just'
        required: false
        default: false
        type: boolean
      just-version:
        description: 'The version of just to install'
        required: false
        default: '1.35.0'
        type: string
      runs-on:
        description: 'The runner to use'
        required: false
        default: 'ubuntu-24.04'
        type: string
      free-disk-space:
        description: 'Free disk space before build'
        required: false
        default: false
        type: boolean

permissions:
  contents: read
  packages: write

jobs:
  pull-request:
    runs-on: ${{ inputs.runs-on }}
    outputs:
      version: ${{ steps.release_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up qemu
        uses: docker/setup-qemu-action@v3

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        if: ${{ inputs.free-disk-space == true }}
        with:
          tool-cache: true

      - name: Next release version
        id: release_version
        uses: getdevopspro/github-actions/release-version@v0.2.19
        with:
          previous-version: ${{ inputs.previous-version }}
          next-version: ${{ inputs.next-version }}
          output-format: ${{ inputs.output-format }}

      - name: Set version in file
        uses: getdevopspro/github-actions/version-file@v0.2.19
        with:
          version: ${{ steps.release_version.outputs.version }}
          version-makefile: ${{ inputs.version-makefile }}
          version-justfile: ${{ inputs.version-justfile }}
          version-package: ${{ inputs.version-package }}
          version-package-lock: ${{ inputs.version-package-lock }}
          version-script: ${{ inputs.version-script }}
          version-chart: ${{ inputs.version-chart }}

      - name: Install just
        if: inputs.just-install
        uses: extractions/setup-just@v2
        with:
          just-version: ${{ inputs.just-version }}

      - name: Run command before build
        if: inputs.build-container-image-pre-command != ''
        id: build_container_image_pre_command
        shell: bash
        run: ${{ inputs.build-container-image-pre-command }}

      - name: Build container image
        uses: getdevopspro/github-actions/buildx-bake@v0.2.20
        id: build_container_image
        with:
          bake-file: ${{ inputs.bake-file }}
          bake-push: ${{ inputs.bake-push }}
          bake-targets: ${{ inputs.bake-targets }}
          bake-set: ${{ inputs.bake-set }}
          bake-extra-files: ${{ inputs.bake-extra-files }}
          image-name: ${{ inputs.image-name }}
          registry: ${{ inputs.registry }}
          registry-username: ${{ inputs.registry-username }}
          registry-password: ${{ secrets.registry-password }}
          meta-labels:
            manifest:org.opencontainers.image.version=${{ steps.release_version.outputs.version }}
            ${{ inputs.meta-labels }}
          meta-tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}},value=${{ steps.release_version.outputs.version }},enable={{is_default_branch}}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.release_version.outputs.version }},enable={{is_default_branch}}
            type=semver,pattern={{major}},value=${{ steps.release_version.outputs.version }},enable={{is_default_branch}}
            type=edge,branch=$repo.default_branch,event=push
            type=sha,event=push
            type=ref,event=branch
            type=ref,event=pr
            ${{ inputs.meta-tags }}
